### ISSUE TITLE
broken on heroku?

### ISSUE THREAD

**Issue by step21** [optional-is/html2pdf#3]
Is it just me or is this somehow broken on heroku? It always fails on starting python app or 'recompiling' it. Further details on request :)

**Comment by step21** [comment]
Ok, now with a change of buildpacks in app.json it runs - but creating a pdf still fails with worker timeout and a phantom.js error. Does it need larger Dynos? I would prefer to run it on the free one.
Phantom.js error:
`TypeError: undefined is not an object (evaluating 'phantom.args.length')
2016-10-26T18:45:01.682496+00:00 app[web.1]:   phantomjs://code/rasterize_pdf.js:4 in global code`

**Comment by briansuda** [comment]
This will work on Heroku with a single Dyno. PhantomJS was updated and args is deprecated. Let me fix it and push the change in a bit.

**Comment by step21** [comment]
Ok, thanks for the feedback, that would be great.

**Comment by briansuda** [comment]
OK, i have updated the app.json to also include python. I tested it and everything is working, you'll probably have to start over and deploy it all again to get it working.
